# Neighborhood.where("'10457' = ANY (neighborhoods.zip_code)")[0].neighborhood
Neighborhood.create(neighborhood: 'Central Bronx', zip_code: [10453, 10457, 10460])
Neighborhood.create(neighborhood: 'Bronx Park and Fordham', zip_code: [10458, 10467, 10468])
Neighborhood.create(neighborhood: 'High Bridge and Morrisania', zip_code: [10451, 10452, 10456])
Neighborhood.create(neighborhood: 'Hunts Point and Mott Haven', zip_code: [10454, 10455, 10459, 10474])
Neighborhood.create(neighborhood: 'Kingsbridge and Riverdale', zip_code: [10463, 10471])
Neighborhood.create(neighborhood: 'Northeast Bronx', zip_code: [10466, 10469, 10470, 10475])
Neighborhood.create(neighborhood: 'Southeast Bronx', zip_code: [10461, 10462,10464, 10465, 10472, 10473])
Neighborhood.create(neighborhood: 'Central Brooklyn', zip_code: [11212, 11213, 11216, 11233, 11238])
Neighborhood.create(neighborhood: 'Southwest Brooklyn', zip_code: [11209, 11214, 11228])
Neighborhood.create(neighborhood: 'Borough Park', zip_code: [11204, 11218, 11219, 11230])
Neighborhood.create(neighborhood: 'Canarsie and Flatlands', zip_code: [11234, 11236, 11239])
Neighborhood.create(neighborhood: 'Southern Brooklyn', zip_code: [11223, 11224, 11229, 11235])
Neighborhood.create(neighborhood: 'Northwest Brooklyn', zip_code: [11201, 11205, 11215, 11217, 11231])
Neighborhood.create(neighborhood: 'Flatbush', zip_code: [11203, 11210, 11225, 11226])
Neighborhood.create(neighborhood: 'East New York and New Lots', zip_code: [11207, 11208])
Neighborhood.create(neighborhood: 'Greenpoint', zip_code: [11211, 11222])
Neighborhood.create(neighborhood: 'Sunset Park', zip_code: [11220, 11232])
Neighborhood.create(neighborhood: 'Bushwick and Williamsburg', zip_code: [11206, 11221, 11237])
Neighborhood.create(neighborhood: 'Central Harlem', zip_code: [10026, 10027, 10030, 10037, 10039])
Neighborhood.create(neighborhood: 'Chelsea and Clinton', zip_code: [10001, 10011, 10018, 10019, 10020, 10036])
Neighborhood.create(neighborhood: 'East Harlem', zip_code: [10029, 10035])
Neighborhood.create(neighborhood: 'Gramercy Park and Murray Hill', zip_code: [10010, 10016, 10017, 10022])
Neighborhood.create(neighborhood: 'Greenwich Village and Soho', zip_code: [10012, 10013, 10014])
Neighborhood.create(neighborhood: 'Lower Manhattan', zip_code: [10004, 10005, 10006, 10007, 10038, 10280])
Neighborhood.create(neighborhood: 'Lower East Side', zip_code: [10002, 10003, 10009])
Neighborhood.create(neighborhood: 'Upper East Side', zip_code: [10021, 10028, 10044, 10065, 10075, 10128])
Neighborhood.create(neighborhood: 'Upper West Side', zip_code: [10023, 10024, 10025])
Neighborhood.create(neighborhood: 'Inwood and Washington Heights', zip_code: [10031, 10032, 10033, 10034, 10040])
Neighborhood.create(neighborhood: 'Northeast Queens', zip_code: [11361, 11362, 11363, 11364])
Neighborhood.create(neighborhood: 'North Queens', zip_code: [11354, 11355, 11356, 11357, 11358, 11359, 11360])
Neighborhood.create(neighborhood: 'Central Queens', zip_code: [11365, 11366, 11367])
Neighborhood.create(neighborhood: 'Jamaica', zip_code: [11412, 11423, 11432, 11433, 11434, 11435, 11436])
Neighborhood.create(neighborhood: 'Northwest Queens', zip_code: [11101, 11102, 11103, 11104, 11105, 11106])
Neighborhood.create(neighborhood: 'West Central Queens', zip_code: [11374, 11375, 11379, 11385])
Neighborhood.create(neighborhood: 'Rockaways', zip_code: [11691, 11692, 11693, 11694, 11695, 11697])
Neighborhood.create(neighborhood: 'Southeast Queens', zip_code: [11004, 11005, 11411, 11413, 11422, 11426, 11427, 11428, 11429])
Neighborhood.create(neighborhood: 'Southwest Queens', zip_code: [11414, 11415, 11416, 11417, 11418, 11419, 11420, 11421])
Neighborhood.create(neighborhood: 'West Queens', zip_code: [11368, 11369, 11370, 11372, 11373, 11377, 11378])
Neighborhood.create(neighborhood: 'Port Richmond', zip_code: [10302, 10303, 10310])
Neighborhood.create(neighborhood: 'South Shore', zip_code: [10306, 10307, 10308, 10309, 10312])
Neighborhood.create(neighborhood: 'Stapleton and St. George', zip_code: [10301, 10304, 10305])
Neighborhood.create(neighborhood: 'Mid-Island', zip_code: [10314])
Advice.create(advice: "It's a smile, it's a kiss, it's a sip of wine ... it's summertime!", category: 'warm')
Advice.create(advice: 'In summer, the song sings itself', category: 'warm')
Advice.create(advice: "Cause a little bit of summer is what the whole year is all about", category: 'warm')
Advice.create(advice: "Friends, sun, sand, and sea, that sounds like a summer to me", category: 'warm')
Advice.create(advice: "Everything good, everything magical happens between the months of June and August", category: 'warm')
Advice.create(advice: "Summertime is always the best of what might be", category: 'warm')
Advice.create(advice: "Keep your face to the sun and you will never see the shadows", category: 'warm')
Advice.create(advice: "Where there is sunshine, the doctor starves", category: 'warm')
Advice.create(advice: "Live in the sunshine, swim the sea, drink the wild air...", category: 'warm')
Advice.create(advice: "Sunshine is a welcome thing. It brings a lot of brightness", category: 'warm')
Advice.create(advice: "One benefit of summer was that each day we had more light to read by", category: 'warm')
Advice.create(advice: "Keep calm and survive the summer..", category: 'warm')
Advice.create(advice: "Hello summer! How I’ve missed you and your lack of responsibilities.", category: 'warm')
Advice.create(advice: "Tan skin; crazy days; late nights: Happy Summer!", category: 'warm')
Advice.create(advice: "Having fun in the sun, getting laid in the shade , summer’s here…..", category: 'warm')
Advice.create(advice: "The warm weather has arrived!", category: 'warm')
Advice.create(advice: "Seas The Day!", category: 'warm')
Advice.create(advice: "here's to a fabulous summer wherever you are", category: 'warm')
Advice.create(advice: "stay cool!", category: 'warm')
Advice.create(advice: "Be like the flower, turn your face to the sun.", category: 'warm')
Advice.create(advice: "Celebrate Summer - Sun drenched days and starlit nights...", category: 'warm')
Advice.create(advice: "It was a splendid summer morning and it seemed as if nothing could go wrong.", category: 'warm')
Advice.create(advice: "Summer is delicious", category: 'warm')
Advice.create(advice: "Who has not dreamed a world of bliss on a bright, sunny noon like this?", category: 'warm')
Advice.create(advice: "You can never appreciate the shade of a tree unless you sweat in the sun", category: 'warm')
Advice.create(advice: "If it could only be like this always – always summer, always alone, the fruit always ripe and Aloysius in a good temper...", category: 'warm')
Advice.create(advice: "I wish we could just fast forward to summer.", category: 'cold')
Advice.create(advice: "Summer should get a speeding ticket.", category: 'cold')
Advice.create(advice: "Where the heck did summer go?", category: 'cold')
Advice.create(advice: "So can we just skip to summer now??", category: 'cold')
Advice.create(advice: "Summer, please restart yourself.", category: 'cold')
Advice.create(advice: "I love the scents of winter, it's all about the feeling you get when you smell pumpkin spice, cinnamon, nutmeg, gingerbread and spruce", category: 'cold')
Advice.create(advice: "Nature’s way of saying, Up, up and away is through winter.", category: 'cold')
Advice.create(advice: "There is nothing that excites me more than planning for summer during the winter months.", category: 'cold')
Advice.create(advice: "Winter is the spring of genius", category: 'cold')
Advice.create(advice: "It is the artist's business to create sunshine when the sun fails", category: 'cold')
Advice.create(advice: "No warm memories visit someone if their winter is cold.", category: 'cold')
Advice.create(advice: "Winter gives me peace, a time to reflect, and moments to spend with myself.", category: 'cold')
Advice.create(advice: "Nobody could stop winter from coming.", category: 'cold')
Advice.create(advice: "The long winter cold gives us new hope for the spring to come.", category: 'cold')
Advice.create(advice: "In the cold dark days of the winter, dream about the flowers to get warmed up!", category: 'cold')
Advice.create(advice: "Like the cold weather. It means you get work done.", category: 'cold')
Advice.create(advice: "What good is the warmth of summer, without the cold of winter to give it sweetness", category: 'cold')
Advice.create(advice: "One thing about cold weather: it brings out the statistician in everyone.", category: 'cold')
Advice.create(advice: "Who knows how long the cold weather will last", category: 'cold')
Advice.create(advice: "Spending time outdoors makes you feel great", category: 'outdoor')
Advice.create(advice: "Be an outdoors kind of guy", category: 'outdoor')
Advice.create(advice: "We have nothing to lose and a world to see", category: 'outdoor')
Advice.create(advice: "Sky above me, earth below me, fire within me", category: 'outdoor')
Advice.create(advice: "The outside is the only place we can truly be inside the world.", category: 'outdoor')
Advice.create(advice: "The sky is the beginning of the limit", category: 'outdoor')
Advice.create(advice: "Excuse me while I kiss the sky", category: 'outdoor')
Advice.create(advice: "The sky, the sky beyond the door is blue", category: 'outdoor')
Advice.create(advice: "Let the sky by your witness", category: 'outdoor')
Advice.create(advice: "Start a painting with the sky", category: 'outdoor')
Advice.create(advice: "Every day is a good day to be alive, whether the sun's shining or not", category: 'outdoor')
Advice.create(advice: "The sun is new each day", category: 'outdoor')
Advice.create(advice: "The sun shines everywhere, not just at the beach", category: 'outdoor')
Advice.create(advice: "The Sun, Moon and Stars are there to guide us", category: 'outdoor')
Advice.create(advice: "Near the sun is the center of the universe", category: 'outdoor')
Advice.create(advice: "Your skin is 24 karat gold when a sun hit it", category: 'outdoor')
Advice.create(advice: "Land is the secure ground of home, the sea is like life, the outside, the unknown", category: 'outdoor')
